README.md:
	touch ~/Desktop/README.md
	echo "#Shashwat Katiyar" >>~/Desktop/README.md
	echo "## Mumbai,Maharashtra,India" >>~/Desktop/README.md
	echo "##Hobbies" >>~/Desktop/README.md
	echo "-playing computer games">>~/Desktop/README.md
	echo "-watching TV series">>~/Desktop/README.md
	echo "##College">>~/Desktop/README.md
	echo "VIT VELLORE- [checkout](http://www.vit.ac.in)">>~/Desktop/README.md
